services:
  - type: web
    name: lavalust
    runtime: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://naling-crud.onrender.com/
      - key: DB_DRIVER
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_CHARSET
        value: utf8mb4
      - key: DB_PREFIX
        value: ""